source 'http://www.rubygems.org/'
ruby '2.0.0'

gem 'sinatra', '1.4.4'
gem 'activerecord', '4.0.4'
gem "sinatra-activerecord", '1.4.0'
gem "sinatra-flash"

gem 'bcrypt'

gem "rake", '10.1.1'

gem 'mysql2', '0.3.15'

gem 'shotgun'
gem "sqlite3"
gem "unicorn"

gem 'carrierwave'
gem 'sinatra-contrib'
gem 'php'

# gem 'sinatra', '1.3.1'
# gem 'activerecord', '3.2.13'
# # gem 'activerecord-mysql2-adapter'
# gem "mysql2"
# gem "sinatra-activerecord"
# gem 'shotgun'
# gem "rake"
# gem "sqlite3"

# gem 'sinatra'
# gem 'activerecord'
# gem "sinatra-activerecord"
# gem "rake"
# gem 'mysql2'
# gem 'shotgun'
# gem "sqlite3"
# # gem 'activerecord-mysql2-adapter'
# gem "unicorn"
# gem 'carrierwave'