source 'http://www.rubygems.org/'
ruby '2.0.0'

gem 'sinatra', '1.3.1'
gem 'activerecord', '3.2.13'
gem 'activerecord-mysql2-adapter'
gem "mysql2"
# gem 'sinatra'
gem "sinatra-activerecord"

gem 'shotgun'
gem "rake"


# group :development do
#   gem "sqlite3"
# end

# group :production do
#   gem "mysql2"
# end

gem "sqlite3"
# gem "mysql2"

