######################################################################
# Automatically generated by qmake (3.0) ? 3? 13 22:47:15 2014
######################################################################

TEMPLATE = app
TARGET = MiddleWare
INCLUDEPATH += .

# Input
SOURCES += testWebAPI.cpp
